"""bug fix

Revision ID: 16d4abd6bf8b
Revises: 560d48155ce7
Create Date: 2024-07-09 15:34:03.040888

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16d4abd6bf8b'
down_revision = '560d48155ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
