"""add pic list

Revision ID: 2a1f329c2dc1
Revises: 0d56cbf41321
Create Date: 2024-06-22 12:58:48.823239

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a1f329c2dc1'
down_revision = '0d56cbf41321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grower', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grower', sa.Column('crop_type_pic', sa.JSON(), nullable=True))
    op.alter_column('grower', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('grower', 'seed_purchase_receipt')
    op.drop_column('grower', 'company_logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grower', sa.Column('company_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('grower', sa.Column('seed_purchase_receipt', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('grower', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('grower', 'crop_type_pic')
    op.drop_column('grower', 'email')
    # ### end Alembic commands ###
