"""add login form

Revision ID: 2dd6f9bb5904
Revises: ba1adf02d45b
Create Date: 2024-07-09 02:08:21.786112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '2dd6f9bb5904'
down_revision = 'ba1adf02d45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grower', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grower', 'user', ['user_id'], ['id'])
    op.add_column('middleman', sa.Column('user_id',
                                         sa.Integer(),
                                         nullable=True))
    op.create_foreign_key(None, 'middleman', 'user', ['user_id'], ['id'])
    op.add_column(
        'user',
        sa.Column('phone',
                  sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False,
                  server_default=''))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_column('user', 'phone')
    op.drop_constraint(None, 'middleman', type_='foreignkey')
    op.drop_column('middleman', 'user_id')
    op.drop_constraint(None, 'grower', type_='foreignkey')
    op.drop_column('grower', 'user_id')
    # ### end Alembic commands ###
