"""Update Product and Transaction relationship

Revision ID: 306822858b49
Revises: ea7efdf05a1e
Create Date: 2024-07-06 06:42:12.940786

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "306822858b49"
down_revision = "ea7efdf05a1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "transaction", "product", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.alter_column(
        "transaction", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
