"""try to fix bug

Revision ID: 33536bae66e8
Revises: eb76785e9400
Create Date: 2024-06-22 16:15:12.462423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '33536bae66e8'
down_revision = 'eb76785e9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
