"""change column

Revision ID: 44940f6dfd09
Revises: 6c7f58f6dc19
Create Date: 2024-06-22 17:03:28.046720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44940f6dfd09'
down_revision = '6c7f58f6dc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('middleman', 'transaction_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('middleman', 'transaction_volume',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
