"""add growerout

Revision ID: 549ed7a6b114
Revises: 2a1f329c2dc1
Create Date: 2024-06-22 13:40:37.536578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '549ed7a6b114'
down_revision = '2a1f329c2dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grower', sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grower', sa.Column('business_license_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grower', 'business_license_photo')
    op.drop_column('grower', 'company_name')
    # ### end Alembic commands ###
