"""change grower middleman

Revision ID: 560d48155ce7
Revises: 995232bf495d
Create Date: 2024-07-09 15:26:48.150521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '560d48155ce7'
down_revision = '995232bf495d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('middleman_purchase_from_middleman_id_fkey', 'middleman', type_='foreignkey')
    op.drop_column('middleman', 'purchase_from_middleman_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchase_from_middleman_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('middleman_purchase_from_middleman_id_fkey', 'middleman', 'middleman', ['purchase_from_middleman_id'], ['id'])
    # ### end Alembic commands ###
