"""add trac info

Revision ID: 584dd1ec1700
Revises: 16d4abd6bf8b
Create Date: 2024-07-10 02:55:04.834549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '584dd1ec1700'
down_revision = '16d4abd6bf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('transaction_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('middleman', 'transaction_info')
    # ### end Alembic commands ###
