"""jianhuaziduan

Revision ID: 6bc32251c3e1
Revises: 8a061938434c
Create Date: 2024-06-22 16:28:25.843638

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6bc32251c3e1'
down_revision = '8a061938434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchase_from_middleman_id', sa.Integer(), nullable=True))
    op.drop_constraint('middleman_sale_to_id_fkey', 'middleman', type_='foreignkey')
    op.create_foreign_key(None, 'middleman', 'middleman', ['purchase_from_middleman_id'], ['id'])
    op.drop_column('middleman', 'sale_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('sale_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'middleman', type_='foreignkey')
    op.create_foreign_key('middleman_sale_to_id_fkey', 'middleman', 'middleman', ['sale_to_id'], ['id'])
    op.drop_column('middleman', 'purchase_from_middleman_id')
    # ### end Alembic commands ###
