"""fix qrcode

Revision ID: 6c7f58f6dc19
Revises: cf1e55859ee7
Create Date: 2024-06-22 16:51:34.978467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c7f58f6dc19'
down_revision = 'cf1e55859ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
