"""change middleman

Revision ID: 7f41be758c1f
Revises: 2dd6f9bb5904
Create Date: 2024-07-09 10:35:12.441107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f41be758c1f'
down_revision = '2dd6f9bb5904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchased_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('purchased_quantity', sa.Float(), nullable=True))
    op.add_column('middleman', sa.Column('purchase_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('transaction_contract_images', sa.JSON(), nullable=True))
    op.add_column('middleman', sa.Column('split_quantities', sa.JSON(), nullable=True))
    op.add_column('middleman', sa.Column('split_qr_codes', sa.JSON(), nullable=True))
    op.add_column('middleman', sa.Column('original_split', sa.JSON(), nullable=True))
    op.add_column('middleman', sa.Column('original_qr_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('middleman', 'original_qr_codes')
    op.drop_column('middleman', 'original_split')
    op.drop_column('middleman', 'split_qr_codes')
    op.drop_column('middleman', 'split_quantities')
    op.drop_column('middleman', 'transaction_contract_images')
    op.drop_column('middleman', 'purchase_source')
    op.drop_column('middleman', 'purchased_quantity')
    op.drop_column('middleman', 'purchased_product')
    # ### end Alembic commands ###
