"""add some sxx

Revision ID: 8ea5406280fb
Revises: e6a8017b5294
Create Date: 2024-07-06 08:22:10.029648

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ea5406280fb"
down_revision = "e6a8017b5294"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grower", sa.Column("total_planting_area", sa.Float(), nullable=True))
    op.add_column("plot", sa.Column("area", sa.Float(), nullable=True))
    op.add_column("plot", sa.Column("planting_date", sa.Date(), nullable=True))
    op.add_column("plot", sa.Column("expected_harvest_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plot", "expected_harvest_date")
    op.drop_column("plot", "planting_date")
    op.drop_column("plot", "area")
    op.drop_column("grower", "total_planting_area")
    # ### end Alembic commands ###
