"""change middleman

Revision ID: 995232bf495d
Revises: 7f41be758c1f
Create Date: 2024-07-09 14:54:38.890399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '995232bf495d'
down_revision = '7f41be758c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchase_from_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('remaining_quantity', sa.Float(), nullable=True))
    op.drop_constraint('middleman_purchase_from_id_fkey', 'middleman', type_='foreignkey')
    op.drop_column('middleman', 'purchase_type')
    op.drop_column('middleman', 'purchase_source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchase_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('middleman', sa.Column('purchase_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('middleman_purchase_from_id_fkey', 'middleman', 'grower', ['purchase_from_id'], ['id'])
    op.drop_column('middleman', 'remaining_quantity')
    op.drop_column('middleman', 'purchase_from_type')
    # ### end Alembic commands ###
