"""change qrcode

Revision ID: ba1adf02d45b
Revises: edfec4d36bc4
Create Date: 2024-07-07 08:20:59.913481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba1adf02d45b'
down_revision = 'edfec4d36bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'qr_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'qr_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
