"""Update relationship fields

Revision ID: cf1e55859ee7
Revises: 6bc32251c3e1
Create Date: 2024-06-22 16:39:23.900125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf1e55859ee7'
down_revision = '6bc32251c3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
