"""Fix model relationships

Revision ID: e6a8017b5294
Revises: 306822858b49
Create Date: 2024-07-06 07:17:35.324961

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6a8017b5294"
down_revision = "306822858b49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "buyer_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "transaction", "middleman", ["buyer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.alter_column(
        "transaction", "buyer_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
