"""change middle man

Revision ID: edfec4d36bc4
Revises: 8ea5406280fb
Create Date: 2024-07-06 18:40:47.743746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'edfec4d36bc4'
down_revision = '8ea5406280fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
