"""change middleman

Revision ID: f14779c57225
Revises: 549ed7a6b114
Create Date: 2024-06-22 15:57:29.253366

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f14779c57225'
down_revision = '549ed7a6b114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'grower', ['id_card_number'])
    op.add_column('middleman', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('middleman', sa.Column('purchase_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('middleman', sa.Column('transaction_volume', sa.Float(), nullable=False))
    op.add_column('middleman', sa.Column('location_coordinates', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('purchase_from_id', sa.Integer(), nullable=True))
    op.add_column('middleman', sa.Column('sale_to_id', sa.Integer(), nullable=True))
    op.add_column('middleman', sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('business_license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('business_license_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('middleman', sa.Column('transaction_contracts', sa.JSON(), nullable=True))
    op.alter_column('middleman', 'id_card_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('middleman', 'id_card_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('middleman_purchase_from_fkey', 'middleman', type_='foreignkey')
    op.create_foreign_key(None, 'middleman', 'middleman', ['sale_to_id'], ['id'])
    op.create_foreign_key(None, 'middleman', 'grower', ['purchase_from_id'], ['id'])
    op.drop_column('middleman', 'purchase_contract')
    op.drop_column('middleman', 'sale_to')
    op.drop_column('middleman', 'purchase_details')
    op.drop_column('middleman', 'sale_details')
    op.drop_column('middleman', 'purchase_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('middleman', sa.Column('purchase_from', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('middleman', sa.Column('sale_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('middleman', sa.Column('purchase_details', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('middleman', sa.Column('sale_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('middleman', sa.Column('purchase_contract', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'middleman', type_='foreignkey')
    op.drop_constraint(None, 'middleman', type_='foreignkey')
    op.create_foreign_key('middleman_purchase_from_fkey', 'middleman', 'grower', ['purchase_from'], ['id'])
    op.alter_column('middleman', 'id_card_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('middleman', 'id_card_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('middleman', 'transaction_contracts')
    op.drop_column('middleman', 'business_license_photo')
    op.drop_column('middleman', 'business_license_number')
    op.drop_column('middleman', 'company_name')
    op.drop_column('middleman', 'sale_to_id')
    op.drop_column('middleman', 'purchase_from_id')
    op.drop_column('middleman', 'location_coordinates')
    op.drop_column('middleman', 'transaction_volume')
    op.drop_column('middleman', 'purchase_type')
    op.drop_column('middleman', 'type')
    op.drop_constraint(None, 'grower', type_='unique')
    # ### end Alembic commands ###
