"""first commit

Revision ID: f910ece7c570
Revises: e2412789c190
Create Date: 2024-06-20 06:18:31.137496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f910ece7c570'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verification_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grower',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_coordinates', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('crop_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crop_yield', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_card_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('land_ownership_certificate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seed_purchase_receipt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qrcode',
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('middleman',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sale_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_card_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_from', sa.Integer(), nullable=True),
    sa.Column('sale_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_contract', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_from'], ['grower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer',
    sa.Column('purchase_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traceability_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('middleman_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['middleman_id'], ['middleman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer')
    op.drop_table('middleman')
    op.drop_table('qrcode')
    op.drop_table('grower')
    op.drop_table('authentication')
    # ### end Alembic commands ###
